name: Run Test

on:
    pull_request: null
    push:
        branches:
            - main

    schedule:
        # see https://crontab.guru/every-day-8am
        - cron: 0 8 * * *

jobs:
    run_test:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Rector'
                        run: composer require rector/rector:dev-main --dev

        name: ${{ matrix.actions.name }}

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}

            -   run: vendor/bin/phpunit
